import 'dart:io' show Platform;

import 'package:flutter/foundation.dart';

mixin class ApiConstant {
  static String get baseUrl {
    if (!kDebugMode) return 'https://api.unicorn-class.com/api/';
    if (Platform.isAndroid) return 'http://10.0.2.2:3000/api/';
    return 'http://localhost:3000/api/';
  }
  static const String loginUrl = 'auth/login';
  static const String teacherBySlugUrl = 'listing/teacherBySlug/';
  static const String parentBySlugUrl = 'listing/parentBySlug/';
  static const String uploadImageUrl = 'auth/images';
  static const String editTeacherProfileUrl = 'update/updateTeacher/';
  static const String editParentProfileUrl = 'update/updateParent/';
  static const String countryUrl = 'location/countries';
  static const String cityUrl = 'location/cities';
  static const String stateUrl = 'location/states';
  static const String getAllClassUrl = 'class/getAllClass';
  static const String listStudentByClassUrl = 'class/ListStudentByClass/';
  static const String addPostUrl = 'post/addPost';
  static const String studentBySlugUrl = 'listing/studentBySlug/';
  static const String studentListByClassUrl = 'attendence/getStudentListByClass';
  static const String markAttendanceUrl = 'attendence/markAttendance';
  static const String resetPasswordUrl = 'password/resetPassword';
  static const String teacherLeaveUrl = 'leave/listTeacherLeaves';
  static const String addTeacherLeaveUrl = 'leave/teacherLeave';
  static const String teacherHolidayEventListUrl = 'holidayEvent/getHolidayEventList';
  static const String reportStudentDetailsUrl = 'report/listReport/';
  static const String studentNurseReportsUrl =
      'report/listStudentNurseReports/';
  static const String evaluationAreaListUrl = 'evaluation/questions/areas';
  static const String evaluationQuestionListUrl = 'evaluation/questions/list';
  static const String evaluationFormsListUrl = 'evaluation/forms/list';
  static const String saveEvaluationFormUrl = 'evaluation/forms/save';
  static const String evaluationFormDetailUrl = 'evaluation/forms/detail/';
  static const String evaluationModuleUrl = 'evaluation/module';
  static const String addMealSnackUrl = 'report/Addmeal/';
  static const String updateMealUrl = 'report/updateMeal/';
  static const String deleteMealUrl = 'report/deleteMeal/';
  static const String mealSnackListUrl = 'report/Listmeal/';
  static const String addNapUrl = 'report/createNap/';
  static const String updateNapUrl = 'report/updateNap/';
  static const String deleteNapUrl = 'report/deleteNap/';
  static const String napListUrl = 'report/listNap/';
  static const String addActivityUrl = 'report/createActivity/';
  static const String activityListUrl = 'report/listActivity/';
  static const String addHygieneUrl = 'report/createHygiene/';
  static const String updateHygieneUrl = 'report/updateHygiene/';
  static const String deleteHygieneUrl = 'report/deleteHygiene/';
  static const String hygieneListUrl = 'report/listHygiene/';
  static const String addNoteUrl = 'report/addNote/';
  static const String noteListUrl = 'report/listNotes/';
  static const String postListUrl = 'post/listPost';
  static const String deletePostUrl = 'post/deletePost/';
  static const String likePostUrl = 'like/addLike/';
  static const String savePostUrl = 'save/savePost/';
  static const String addCommentUrl = 'comment/addComment/';
  static const String updateCommentUrl = 'comment/updateComment/';
  static const String deleteCommentUrl = 'comment/deleteComment/';
  static const String addStoryUrl = 'story/addStory';
  static const String storyListUrl = 'story/listStories';
  static const String deleteStoryUrl = 'story/deleteStory/';
  static const String uploadVideoUrl = 'auth/videos';
  static const String updateStudentUrl = 'update/updateStudent/';
  static const String feesDetailsUrl = 'fee/FeesdetailsById/';
  static const String galleryListUrl = 'gallery/list/';
  static const String parentListUrl = 'listing/listParents';
  static const String teacherListUrl = 'listing/listTeachers';
  static const String forgotPasswordUrl = 'password/forgotPassword';
  static const String verifyOtpUrl = 'password/verifyOtp';
  static const String moodUpdateUrl = 'report/updateMood/';
  static const String parentListingUrl = 'teacherChat/parentListing';
  static const String createChatUrl = 'teacherChat/createChat_P&T';
  static const String teacherGroupUserList = 'nurseryTeacherChat/teacherGroupUserList';
  static const String parentGroupUserList = 'nurseryParentChat/parentGroupUserList';
  static const String storyViewApi = 'story/viewStory/';
  static const String storyViewListApi = 'story/listStoryView/';
  static const String storyLikeListApi = 'story/storyLike/';
  static const String replyCommentApi = 'comment/commentReply/';
  static const String changePasswordApi = 'password/changePassword';
  static const String notificationListApi = 'notification/list';
  static const String notificationMarkAsReadApi = 'notification/markAsRead';
  static const String notificationMarkAllReadApi = 'notification/markAllRead';
  static const String updateFcmTokenUrl = 'auth/fcmToken';
  static const String likeListApi = 'like/listLike/';
  static const String updateMood = 'report/updateMood/';
  static const String addStudentLeave = 'leave/studentLeave';
  static const String studentLeaveList = 'leave/listStudentLeaves';
}
